service: chat-gpt-slack-bot
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  timeout: 180
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /slack/events
          method: post
          cors: true
plugins:
  - serverless-offline